apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-deployment
  template:
    metadata:
      labels:
        app: django-deployment
    spec:
      containers:
      - name: django-deployment
        image: localhost:5000/django-codalab
        command: ["/app/docker/run_django.sh"]
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: config


---
apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    name: django
spec:
  ports:
    - port: 8000
      protocol: TCP
      name: server
  selector:
    app: django-deployment
  type: ClusterIP
