apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
      - name: postgres-deployment
        image: localhost:5000/postgres-codalab
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: config
        env:
          - name: POSTGRES_DB
            value: "codalab_website"
          - name: POSTGRES_USER
            value: "root"
          - name: POSTGRES_PASSWORD
            value: "password"


---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
      name: server
  selector:
    app: postgres-deployment
  type: ClusterIP